# Generated by Django 5.1.4 on 2025-01-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='save_chat',
            field=models.BooleanField(default=False),
        ),
    ]
