# Generated by Django 5.1.4 on 2024-12-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('display', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sector_id', models.PositiveIntegerField()),
                ('role_id', models.PositiveIntegerField()),
                ('model_id', models.PositiveIntegerField()),
                ('save_chat', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Model Configuration',
                'verbose_name_plural': 'Model Configurations',
                'unique_together': {('sector_id', 'role_id', 'model_id')},
            },
        ),
    ]
